### ISSUE TITLE
Step 3: Error:(171, 9) error: cannot find symbol class CollectionReference

### ISSUE THREAD

**Issue by witeshadow** [firebase/friendlyeats-android#11]
Error:(171, 9) error: cannot find symbol class CollectionReference

**Comment by samtstern** [comment]
@witeshadow are you able to find other Firestore classes?  What step of the codelab are you trying to do?

**Comment by samuelgarbo** [comment]
I have the same problem in step 4

**Comment by samtstern** [comment]
@samuelgarbo do you have an import for CollectionReference?

```
import com.google.firebase.firestore.CollectionReference;
```

https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/CollectionReference

**Comment by samuelgarbo** [comment]
Thank you

**Comment by msamancioglu** [comment]
thx
