### ISSUE TITLE
Writing to Firestore

### ISSUE THREAD

**Issue by noahjeffers** [firebase/friendlyeats-android#115]
I have followed the steps up until Step 6, but none of the restaurant data is being stored in the Firestore. My user account gets stored in the Authentication tab, but nothing changes in Firestore. 
The Emulator is running.
The Logcat shows no errors.
![image](https://user-images.githubusercontent.com/59740042/109394663-c1446780-78ed-11eb-884d-dc086f352aeb.png)
This is a snippet of the Logcat after clicking Add Random Items. The objects are created and they send off a com.google.firestore.v1.WriteRequest and there is a WriteResponse (the latter is in the picture above).

I have restarted this project a couple of times and I can't for the life of me figure out the issue

**Comment by samtstern** [comment]
@noahjeffers when you say "none of the restaurant data is being stored in the Firestore" have you checked in both the Emulator UI and the Firebase console? Maybe you have been writing to the wrong place or checking the wrong place to se your data.

**Comment by noahjeffers** [comment]
@samtstern I am checking the Firebase Emulator Suite, because when I sign in, it creates the account and saves it to the Emulator Suite
![image](https://user-images.githubusercontent.com/59740042/109512787-11e0cf80-7a6a-11eb-8403-a9c4a203e192.png)

I currently have both the Firebase Emulator Suite, and the Firebase Console open, and after clicking "Add Random Items" it doesn't save the restaurants to either.

**Comment by samtstern** [comment]
@noahjeffers hmmm well based on those network logs the data is being written to some Firestore somewhere! Maybe you have mismatched  project IDs? Are you sure that your Android app is pointing to the same Firebase project ID that is being used in the Emulator Suite?

**Comment by noahjeffers** [comment]
I have checked the Firestore for the Eats project as well as the Firestore for the previous Friendly Chat project that I did. As well, the Project ID in the Console matches the one in the google-services.json file

**Comment by samtstern** [comment]
@noahjeffers you've got me stumped. That data is going somewhere, either to the emulator or to a real project. I have no idea why you can't see it in any of your UIs

**Comment by noahjeffers** [comment]
I decided to finish the codelab anyways, and much to my surprise it worked. I still dont know where the data was being written to, but the app was able to pull it from there. It just never showed up in the Firestore. Thank you for your help anyways
