### ISSUE TITLE
I'm trying to log in, but I can't log in due to a network error.

### ISSUE THREAD

**Issue by hansungbin** [firebase/friendlyeats-android#132]
I'm going to study Firebase using "Friendly Eats" sample source.
https://firebase.google.com/codelabs/firestore-android#2
I'm proceeding with the explanation number 5(Run the app).

The local emulator ran well.
You also created a account on the Authentication tab at http://localhost:4000/.

When logging in with the email generated from the login screen, the login process is not progressing due to a network error.

What should I do?

**Comment by samtstern** [comment]
@hansungbin what is the network error? Please provide detailed logs so we can help you debug.

**Comment by hansungbin** [comment]
Generally, I didn't test it with a local emulator because I operated it on my phone. 
When I first wrote the question, I only did it on my phone, but it didn't work, so I asked the question.

I accidentally operated on a local emulator and it works well.
![question1](https://user-images.githubusercontent.com/11886510/124543587-82f12300-de60-11eb-9a5c-4688f7aba418.JPG)

But it still doesn't work well on my phone, what should I do?
Other applications work well without any problems.
![question](https://user-images.githubusercontent.com/11886510/124543595-871d4080-de60-11eb-8298-0ccfd337d8f9.JPG)
Is there a way to work well on my phone?

**Comment by samtstern** [comment]
@hansungbin when you're using the Firebase Emulator Suite you can't use a real device, you need to use an Android emulator so that they can communicate over `localhost`.

If you want to use a real device you'll need to use a real Firebase project, which is covered in the final step:
https://firebase.google.com/codelabs/firestore-android#11

**Comment by samtstern** [comment]
I am going to close this issue, but I'll also make sure to add a warning to the codelab to make this clearer.
