### ISSUE TITLE
Step4: ButterKnife, AuthUI, ViewModel, MaterialRatingBar dependencies correction

### ISSUE THREAD

**Issue by bighwstyle** [firebase/friendlyeats-android#18]
For those of who have set up issue like dependencies and deprecated code. Change it as follows.

`  // FirebaseUI (for authentication)
    implementation 'com.firebaseui:firebase-ui-auth:4.0.0'
`

`
    // ButterKnife (for sample code brevity)
    implementation "com.jakewharton:butterknife:8.8.0"
    annotationProcessor "com.jakewharton:butterknife-compiler:8.8.0"
`
...
`
    // Android architecture components
    implementation 'android.arch.lifecycle:extensions:1.1.0'
    implementation 'android.arch.lifecycle:runtime:1.1.0'
    annotationProcessor 'android.arch.lifecycle:compiler:1.1.0'
`

`
    implementation 'me.zhanghai.android.materialratingbar:library:1.3.1'
`

and change the AuthUI.EMAIL...
`
new AuthUI.IdpConfig.EmailBuilder().build()
`

I am not sure it works for those of who have same problem. But it works for me.

**Comment by samtstern** [comment]
See https://github.com/firebase/friendlyeats-android/commit/92a6c39c902dcb35f7a77d1fb6322d773731773d
