### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by erikswed** [firebase/friendlyeats-android#2]
Thanks for the Code lab.
In step 5 "Sort and filter data" there´s a text: "In the logs you will notice some warnings:"
I think there should be an explanation on where this log is located?

**Comment by samtstern** [comment]
@erikswed thanks for the feedback, I will make a change now.

**Comment by samtstern** [comment]
Fixed:
https://codelabs.developers.google.com/codelabs/firestore-android/#4
