### ISSUE TITLE
setQuery to load more documents

### ISSUE THREAD

**Issue by RRGT19** [firebase/friendlyeats-android#25]
Hi,
I'm practicing with your FirebaseAdapter and I'm trying to implement the load more function, I mean, when you scroll down and you reach the end of the screen, the App should load more documents automatically.

This is called "pagination" according to the documentation [here](https://firebase.google.com/docs/firestore/query-data/query-cursors).

I have modified this:
```
public abstract class FirestoreAdapter..........  {
    .....
    ........
    private DocumentSnapshot mLastVisible;

    @Override
    public void onEvent(QuerySnapshot documentSnapshots, FirebaseFirestoreException e) {
        ....
            ..
            ...
            ..
        ..

        ...............
        ...
        onDataChanged();

        // Get the last visible document
        mLastVisible = documentSnapshots.getDocuments().get(documentSnapshots.size() - 1);
    }

public void setQueryForLoadMore(Query query) {
        mQuery = query;
        notifyDataSetChanged();
    }

    public DocumentSnapshot getLastVisible() {
        return mLastVisible;
    }
```

MainActivity:
```
mAdapter.setQueryForLoadMore(loadMoreQuery());

private Query loadMoreQuery() {
        // Return ${LIMIT} documents after the last visible document from first query
        return mFirestore.collection("posts")
                .orderBy("timestamp", Query.Direction.DESCENDING)
                .startAfter(mAdapter.getLastVisible())
                .limit(LIMIT);
    }
```

The new documents seems to be inserted correctly but, is not showing it on the screen.

If I do this:
```
    public void setQueryForLoadMore(Query query) {
        // Stop listening
        //stopListening(); I commented this because this method is clearing mSnapshots

        // Clear existing data
        //mSnapshots.clear(); I commented this because I want to maintain the previous documents
        notifyDataSetChanged();

        // Listen to new query
        mQuery = query;
        startListening(); // If I comment this, still nothing appears after the previous documents
    }
```

Still the new documents are not showing up.

Any idea how can I get the new documents to be added and to show them on the screen? I mean, right after the previous documents.

**Comment by samtstern** [comment]
@RRGT19 apologies for never getting back to you.  I think questions like this are better suited for StackOverflow if your aim is to learn how to do it yourself (or maybe on one of the Firebase mailing lists).

We have implemented a paging adapter in the FirebaseUI-Android library:
https://firebaseopensource.com/projects/firebase/firebaseui-android/firestore/readme.md/

However it does not have support for any real time modifications, so it may not work for your use case.
