### ISSUE TITLE
Step 8: Inaccurate Description

### ISSUE THREAD

**Issue by ronykrell** [firebase/friendlyeats-android#32]
The description of step 8 states:

> ...updates to a restaurant document can only change the ratings, not the name or any other immutable data. 

However, the update rule only makes sure the user is authenticated and the restaurant name is unchanged - any other change to the restaurant object would be possible.

```service cloud.firestore {
  match /databases/{database}/documents {
        // Restaurants:
        //   - Authenticated user can read
        //   - Authenticated user can create/update (for demo)
        //   - Validate updates
        //   - Deletes are not allowed
    match /restaurants/{restaurantId} {
      allow read, create: if request.auth != null;
      allow update: if request.auth != null
                    && request.resource.data.name == resource.data.name
      allow delete: if false;
    `
```

**Comment by samtstern** [comment]
@ronykrell you're right that's a mistake, thanks for reporting this!

**Comment by 2000Vlad** [comment]
mRegistration is null so startListening() cannot attach listener

**Comment by samtstern** [comment]
I made a change to make the rules much better and added a generic example to the snippets-rules repo:
https://github.com/firebase/snippets-rules/pull/9

Thanks @ronykrell
