### ISSUE TITLE
Query filter of cloud firestore does not work properly!?

### ISSUE THREAD

**Issue by OdaiAlqohaly** [firebase/friendlyeats-android#5]
I was trying to implement a filter for querying data from firebase firestore just like the one in the codelab but i could not have it work well , the only way to make that query is by concatenating whereEqaulTo into a single statement otherwise it will not work, in fact ,if you set many whereEqualTo  on the query object each one in a separate statement only the first statement whereEqualTo method is applied . the rest are ignored.
Firebase database have limited abilities when it comes to fetching and filtering data that is because it is no-sql database , having such issue make it even worse for someone who is looking for flexible and complex queries. I hope that  you firebase team will find a solution for this issue soon.

**Comment by samtstern** [comment]
@OdaiAlqohaly can you show the code where you're building your query?  That will help us understand.

**Comment by OdaiAlqohaly** [comment]
`Query query = FirebaseFirestore.getInstance().collection(FirebaseRef.FireStoreRef.ADVERTISEMENTS_COLLECTION);

            query = query.whereEqualTo("propertyStatus", propertyStatus);

        if (!realEstateType.equals("Any")) {
            query = query.whereEqualTo("realEstateType", realEstateType);
        }


        if (!minPrice.equals("Any") && flag) {
            query =  query.whereGreaterThan("propertyPrice", Integer.valueOf(minPrice));
        }
        if (!maxPrice.equals("Any") && flag){
            query = query.whereLessThan("propertyPrice", Integer.valueOf(maxPrice));

        }

        if (!propertyPhysicalConditionS.equals("Any")) {
            query = query.whereEqualTo("propertyCondition", propertyCondition);
        }
        
        query.addSnapshotListener(new EventListener<QuerySnapshot>() {
            @Override
            public void onEvent(QuerySnapshot documentSnapshots, FirebaseFirestoreException e) {


                if (e != null) {
                    Log.d(TAG, "error query");
                    return;
                }
                Log.d(TAG, "onEvent: " + documentSnapshots.size());
                if (!documentSnapshots.isEmpty()) {

                    documentSnapshotArrayList.clear();
                    for (DocumentSnapshot documentSnapshot : documentSnapshots.getDocuments()) {
                        documentSnapshotArrayList.add(documentSnapshot);
                    }

                    searchResultRecyclerViewAdapter.updateAdapterWithNewDocList(documentSnapshotArrayList);
                }else {
                    documentSnapshotArrayList.clear();
                    searchResultRecyclerViewAdapter.updateAdapterWithNewDocList(documentSnapshotArrayList);
                }
            }
        });`

**Comment by erikswed** [comment]
You should create this question at https://stackoverflow.com since it´s not related to friendlyeats but to Firestore. Also you get a hole loot more attention at stackoverflow

**Comment by erikswed** [comment]
Just a quick look, looks like you missed to do 
query = query.whereEqualTo("propertyStatus", propertyStatus);
query =  query.whereEqualTo("realEstateType", realEstateType);
query =query.whereEqualTo("propertyCondition", propertyCondition);

**Comment by OdaiAlqohaly** [comment]
You mean I should assign 
`query.whereEqualTo("city", filters.getCity());`
to the query bject every time set a filter as this:
`query = query.whereEqualTo("city", filters.getCity());`

I'll try that and see.

**Comment by samtstern** [comment]
Thanks @erikswed!  Yes that answer is exactly right, you need to assign to the `query` variable each time.

**Comment by OdaiAlqohaly** [comment]
It works like a charm , It seems that I was missing that part erikswed mentioned thank you so much ,I've posted this issue on stackoverflow but I didn't see any response, thanks.I'll have to close this issue
