### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by FaithLaou** [firebase/friendlyeats-android#72]
Hi, I've been playing with the code and I was wondering why do you need the listener on the Restaurant collection? Let's say I want to remove the listener as there won't be any changes to my restaurant collection, how will you do that?

**Comment by erikswed** [comment]
See the codelab page 5:

> Note: this codelab demonstrates the real-time capabilities of Firestore, but it's also simple to fetch data without a listener. You can call get() on any query or reference to fetch a data snapshot.

https://codelabs.developers.google.com/codelabs/firestore-android/#4

**Comment by FaithLaou** [comment]
Thank you so much for your response my friend! I see what you are saying. So if I just want to display the restaurant names in a list as you do in this code lab but without having a listener, I should not use an adapter? How should this be done? (sorry for this stupid question, I'm still learning and this tutorial has been very helpful) :)

**Comment by erikswed** [comment]
Firestore is all listeners you cant get anything out of any Collection without attaching a listener, this is the way!
Learn and use the adapter that is what i'ts for the and the recommended way. 
Of course you can use the code in adapter and place the code in your `Activity `and run in on `Activity `s tart and it will get you what you need from the collection like it say here read the:
Listen to multiple documents in a collection
https://firebase.google.com/docs/firestore/query-data/get-data
Here is a quick answer
https://stackoverflow.com/questions/50727254/how-to-retrieve-all-documents-from-a-collection-in-firestore

**Comment by FaithLaou** [comment]
Thanks for your response! you said that: "Firestore is all listeners you cant get anything out of any Collection without attaching a listener, this is the way!". Lets say restaurants data won't change in Firestore. Can't we just get the info from a collection, put it in an array of restaurant objects and then display that array in a recyclerView?? (without having to use a listener)

**Comment by erikswed** [comment]
No, you must attach a listener look at this, if you only need it to run one time you can call it singleShotListener for code readability 
https://stackoverflow.com/questions/50727254/how-to-retrieve-all-documents-from-a-collection-in-firestore

**Comment by FaithLaou** [comment]
I agree, Here is what I'm using to retrieve the restaurants data
db.collection("Universities")
            .get()
            .addOnSuccessListener { result ->
                for (document in result) {
                    Log.d(TAG, "${document.id} => ${document.data}")
                }
            }
            .addOnFailureListener { exception ->
                Log.d(TAG, "Error getting documents: ", exception)
            }

Is this OK?

**Comment by erikswed** [comment]
Looks good there are many tutorial on this just [google](https://www.google.com/search?newwindow=1&sxsrf=ACYBGNQ12rnaz6itBUXi5-Kls_It4AN7BA%3A1578279865717&ei=uaMSXsWkK83MwAL3-62YBg&q=firestore++tutorial+get+collection+to+recyclerView&oq=firestore++tutorial+get+collection+to+recyclerView&gs_l=psy-ab.3...27200.27200..27834...0.4..0.188.188.0j1......0....2j1..gws-wiz.......0i71.ReK_Xgzax08&ved=0ahUKEwiF5YHW_u3mAhVNJlAKHfd9C2MQ4dUDCAs&uact=5
)

**Comment by samtstern** [comment]
@FaithLaou @erikswed thanks for having this conversation on GitHub!  It's useful for us to read.

There are two ways you can get the results of a query in Cloud Firestore:

  * `addSnapshotListener()` - gets you one initial result set and then all future updates that affect the results.  
  * `get()` - gets you a single result set from the server.

Internally, `get()` is actually implemented as "attach a listener, get results once, detach the listener" so they're very similar in terms of performance and billing for the first results.

@FaithLaou if you want to use a `get()` to get an array of results and then pass them to a `RecyclerView.Adapter` in memory, that's totally fine.  In this codelab we were just trying to show off the power of using Firestore listeners to get real-time data binding.
