### ISSUE TITLE
Add sample data - error:  onAddItemsClicked()

### ISSUE THREAD

**Issue by rhodyapps** [firebase/friendlyeats-android#74]
Device: Android Studio/Emulator

Project: friendlyeats-android
    compileSdkVersion 29
    buildToolsVersion '29.0.2'
    applicationId 'com.google.firebase.example.fireeats'
    minSdkVersion 16
    targetSdkVersion 29
 
Problem: 
Tutorial Step 4: Write Data to Firestore 
Adding the suggested code to MainActivity onAddItemsClicked() does not recognize the Restaurant class.

Error:
error: cannot find symbol
            Restaurant restaurant = RestaurantUtil.getRandom(this);
   
What steps will reproduce the problem:
1. Clone the repository, follow the tutorial 
2. Add the code in step 4: Write Data to Firestore
3. Build the project

What is the expected result?
The app  builds and runs on the emulator. Sample data is loaded into the restaurants collection in firestore.

What happens instead of that?

Build error:
error: cannot find symbol
            Restaurant restaurant = RestaurantUtil.getRandom(this);
![Screen Shot 2020-02-11 at 9 32 59 AM](https://user-images.githubusercontent.com/12385176/74245919-c4a08d00-4cb1-11ea-817d-a0c6e79b960d.png)

**Comment by samtstern** [comment]
@rhodyapps have you tried importing the `Restaurant` class into `MainActivity`?  If you're using Android Studio it should do this automatically for you if you right click on the red-underlined `Restaurant` name and tell it to import.

**Comment by rhodyapps** [comment]
Hi Sam
Apologies for the late reply I just now saw this in the github notifications, yes this was the way to fix the problem. Thank you!
